[default]
remappings = [
    "forge-std/=lib/forge-std/src/",
    "forge-utils/=lib/forge-utils/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/contracts/",
    "openzeppelin-contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts/",
]
verbosity = 3

[ci]
fuzz-runs = 10_000
